### PR TITLE
add week-3 part-time schedule

### PR DESCRIPTION
**Pull request by josibake**
Bare bones, open to feedback!

Open questions:

- [x] is this a good split for the reading material?
- [x] are there any hands-on exercises we can add so that it's not a reading-only week?
- [x] are there better links for the web book?

### CODE REVIEW

**Comment by stickies-v** [comment]
Updated links to @willcl-ark's hosted version which he kindly agreed we could keep using

**Comment by stickies-v** [comment]
Pace-wise, this looks fine to me. It's half the pace from the full-time seminar, but the full-time seminar actually only allocated only half the time to lnbook, so in relative terms this should be even lower load. Which I think is helpful to give a bit more time to go deep on discussion questions.

Re exercises, I think what we have from full time afternoon works well? https://course.qala.dev/readme/week-2#afternoons

**Comment by tvpeter** [comment]
On the schedule, I think they should be able to cover chapter 3 in a day, and chapter 6 coming on Friday. 

For the deliverables, some of the deliverables from the full-time should be included like:

-  Running LND from source
-  Running the LND test suite 
-  Opening a lightning channel on signet
-  Request an invoice and make a payment

**Comment by josibake** [comment]
> On the schedule, I think they should be able to cover chapter 3 in a day, and chapter 6 coming on Friday.

In the full-time, chapter 3 had a full day. Looking through what they cover, I'm inclined to give them 2 days because chapter 3 covers a lot of the meat of what the lightning network is and I think it's really important they understand it. But you guys remember this from last year, so I might be over-estimating? @stickies-v ?

> For the deliverables, some of the deliverables from the full-time should be included like:
> 
>     * Running LND from source
> 
>     * Running the LND test suite

They have already done this as part of week 1, right?

>     * Opening a lightning channel on signet
> 
>     * Request an invoice and make a payment

^ I'll add these ones in

**Comment by stickies-v** [comment]
I agree with you @josibake, it's an important chapter and I'd rather no one has to rush through. Those that have a bit more time on their hands can hack away at the other projects.

**Review by tvpeter — APPROVED** [review]
Looks great, thanks a lot.

**Pull request merged**
