### PR TITLE
Add folder for 01-2024 fellowship

### PR DESCRIPTION
**Pull request by vladimirfomene**
@tvpeter we have created a new directory for the course content of the current fellowship. Please have a review and merge/give feedback.

### CODE REVIEW

**Comment by tvpeter** [comment]
Please can you make it to be `Btrust-builders-schedule`?

**Comment by vladimirfomene** [comment]
@tvpeter what if we have a new schedule for the second Btrust builders cohort? I used the following format `<month>-<year>-schedule` for the schedule because I think it will help us accommodate future schedules.

**Comment by tvpeter** [comment]
Yes, that's agreed. However, I think the idea was to have a single curriculum and keep improving on it. There was need for a new schedule when the program was changed to part-time and now that the objective has changed, we are having a new one. So I think we should aim for having one and improving it.

**Comment by vladimirfomene** [comment]
I will push back on that a little. I understand your need to have a directory that is improved over time. The issue with that structure is that you lose history of the course content of the previous cohorts.

**Comment by tvpeter** [comment]
Well, I think I will approve it for us to get going while I get Femi's view. In case we have to rename, it won't be an issue. Thanks

**Pull request merged**
